BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers;
   [Area("Admin")]
public class CoverTypeController : Controller
    {
        //private readonly ApplicationDbContext _db;
        //private readonly ICategoryRepository _db;
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork db)
        {
            _unitOfWork = db;
        }

        public IActionResult Index()
        {
            //IEnumerable<Category> objCategoryList = _db.Categories; //retreive the category 
            //IEnumerable<Category> objCategoryList = _db.Category.GetAll(); //retreive the category 
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll(); //to use unityof work.
            return View(objCoverTypeList);
        }

        //Create Functionality
        //GET
        public IActionResult Create() 
        {
            return View();
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(CoverType obj)  //in validation check model is valid or not (Require properties have or not)
        {
            //costom validation
           

            //check properties validation 
            if (ModelState.IsValid)     //havor on ModelState and check(Values>Result Values) if any propertie valid or not here 
            {
                //_db.Categories.Add(obj);   //add to category
                _unitOfWork.CoverType.Add(obj);   //after repo
                //_db.SaveChanges(); //simple use
                //_db.Save(); //after repo
                _unitOfWork.Save(); //after use unitofwork
                TempData["success"] = "CoverType created successfully";
                return RedirectToAction("Index"); 
            }
            return View(obj);
        }



        //Edit/Update Functionality 

        //GET
        public IActionResult Edit(int? id) 
        {
            if (id ==null || id==0)
            {
                return NotFound();
            }
            //way of retreive category
            //var categoryFromDb = _db.Categories.Find(id);  //based on the primary key it find  
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.ID == id); //not throw exception and return first element of the list 
            //var categoryFromDbFirst = _db.GetFirstOrDefault(u=>u.ID == id); //after repo
            var CoverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.CoverType_Id== id); //after use unitofwork
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.ID == id); //throw an exception
            if (CoverTypeFromDb == null) 
            {
                return NotFound();
            }
            return View(CoverTypeFromDb);
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken] 
        public IActionResult Edit(CoverType obj)  //in validation check model is valid or not (Require properties have or not)
        {
            //costom validation
          


            //check properties validation 
            if (ModelState.IsValid)     //havor on ModelState and check(Values>Result Values) if any propertie valid or not here 
            {
                //_db.Categories.Update(obj); //update for this 
                //_db.Update(obj); //after use repo
                _unitOfWork.CoverType.Update(obj); //after use unitofwork
                //_db.SaveChanges();
                //_db.Save(); //after use repo
                _unitOfWork.Save(); //after use unitofwork
                TempData["success"] = " CoverType updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }



        //update functionality
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //way of retreive category
            //var categoryFromDb = _db.Categories.Find(id);  //based on the primary key it find  
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.ID == id); //not throw exception and return first element of the list 
            var CoverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(u=>u. CoverType_Id == id); //after use repo
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.ID == id); //throw an exception
            if (CoverTypeFromDb == null)
            {
                return NotFound();
            }
            return View(CoverTypeFromDb);
        }

        //Post
        [HttpPost,ActionName("Delete")]
        [AutoValidateAntiforgeryToken]  
        public IActionResult DeletePOST(int? id)  //in validation check model is valid or not (Require properties have or not)
        {
            //var obj = _db.Categories.Find(id);
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u => u.CoverType_Id == id); //add line after use repo
            if (obj == null)
            {
                return NotFound();
            }

            //_db.Categories.Remove(obj); //remove for this 
            _unitOfWork.CoverType.Remove(obj); //add after repo
            //_db.SaveChanges();
            _unitOfWork.Save(); //add after unitofwork
            TempData["success"] = " CoverType deleted successfully";
            return RedirectToAction("Index"); 
        }
    }

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public ProductController(IUnitOfWork db, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = db;
        _hostEnvironment = hostEnvironment;
    }
    public IActionResult Index()
    {
        //  IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll(); 
        //  return View(objProductList);
        return View();
    }
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new()
        {
            product = new(),

            CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.ID.ToString()
            }),
            CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
            {
                Text = i.CoverType_Name,
                Value = i.CoverType_Id.ToString()
            }),
        };

        if (id == null || id == 0)
        {
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            return View(productVM);
        }
        else
        {
            productVM.product=_unitOfWork.Product.GetFirstOrDefault(u=>u.Id == id);
            return View(productVM);
        }
        
    }
    //Post
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Images\products");
                var extension = Path.GetExtension(file.FileName);
                if (obj.product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.product.ImageUrl = @"\Images\Products\" + fileName + extension;
            }
            if (obj.product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.product);
            }
            else
            {
                _unitOfWork.Product.Update(obj.product);
            }

            _unitOfWork.Save();
            TempData["success"] = " Product added successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    #region API CALLS

    [HttpGet]

    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
        return Json(new { data = productList });

    }
    [HttpDelete]
    public IActionResult Delete(int? id) 
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id); 
        if (obj == null)
        {
            return Json(new {success=false, message = "Error while deleting"});
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Product.Remove(obj); ;
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete Successful" });
    }
    #endregion
}

BulkyBookWeb/Areas/Admin/Views/Product/Index.cshtml
 
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary ">Product List</h2>
        </div>
         <div class="col-6 text-end">
             <a asp-controller ="Product" asp-action="Upsert" class="btn btn-primary">
                 <i class="bi bi-plus-circle"></i> &nbsp; Create New Product
             </a>
        </div> 
    </div>
    <br/>


<table id ="tblData" class = "table table-bordered table-striped" style="width:100%" >
    <thead>
        <tr>
            <th>Title</th>
            <th>ISBN</th>
            <th>Price</th>
           <th>Author</th>
            <th>Category</th>
            <th></th>
        </tr>
    </thead>
        
</table>
</div>
@section Scripts
{
    <script src = "~/js/product.js">
    </script>
}

BulkyBookWeb/Areas/Admin/Views/Product/Upsert.cshtml
@model BulkyBook.Models.ViewModels.ProductVM

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
   <input asp-for = "product.Id" hidden/> 
   <input asp-for = "product.ImageUrl" hidden/> 
   <div class = "row">
       <div class = "col-10">
            <div class="border p-3 mt-4 row">
                 <div class="row pb-2">
                     <h2 class="text-primary">@(Model.product.Id!=0? "Update" : "Create") Product</h2>
                     <hr />
                 </div>
                 <div class="mb-3">
                     <label asp-for=product.Title></label>
                     <input asp-for="product.Title" class= "form-control"/>
                      <span asp-validation-for="product.Title" class="text-danger"></span> 
                 </div>
                 <div class="mb-3 ">
                    <label asp-for=product.Description></label>
                    <textarea asp-for="product.Description" rows = "3" class= "form-control"></textarea>
                    <span asp-validation-for="product.Description" class="text-danger"></span> 
                </div>
                <div class="mb-3 col-6">
                    <label asp-for=product.ISBN></label>
                    <input asp-for="product.ISBN" class= "form-control"/>
                    <span asp-validation-for="product.ISBN" class="text-danger"></span> 
                </div>
                <div class="mb-3 col-6">
                    <label asp-for=product.Author></label>
                    <input asp-for="product.Author" class= "form-control"/>
                    <span asp-validation-for="product.Author" class="text-danger"></span> 
                </div>
                    <div class="mb-3 col-6">
                        <label asp-for=product.Listprice></label>
                        <input asp-for="product.Listprice" class= "form-control"/>
                        <span asp-validation-for="product.Listprice" class="text-danger"></span> 
                    </div>
                    <div class="mb-3 col-6">
                        <label asp-for=product.Price></label>
                        <input asp-for="product.Price" class= "form-control"/>
                        <span asp-validation-for="product.Price" class="text-danger"></span> 
                    </div>
                    <div class="mb-3 col-6">
                        <label asp-for=product.Price50></label>
                        <input asp-for="product.Price50" class= "form-control"/>
                        <span asp-validation-for="product.Price50" class="text-danger"></span> 
                    </div>
                    <div class="mb-3 col-6">
                         <label asp-for=product.Price100></label>
                         <input asp-for="product.Price100" class= "form-control"/>
                         <span asp-validation-for="product.Price100" class="text-danger"></span> 
                    </div>
                   <div class="mb-3 ">
                        <label asp-for=product.ImageUrl></label>
                        <input type = "file" id = "uploadBox" name = "file" class= "form-control"/>
                   </div>
                   <div class="mb-3 col-6">
                        <label asp-for=product.CategoryId></label>
                        <select asp-for="product.CategoryId" asp-items="@Model.CategoryList"  class= "form-select">
                        <option disabled selected>--Select Category-- </option> 
                        </select>
                        <span asp-validation-for="product.CategoryId" class="text-danger"></span> 
                    </div>
                    <div class="mb-3 col-6">
                        <label asp-for=product.CoverTypeId></label>
                        <select asp-for="product.CoverTypeId" asp-items="@Model.CoverTypeList"  class= "form-select">
                        <option disabled selected>--Select CoverType-- </option> 
                        </select>
                        <span asp-validation-for="product.CoverTypeId" class="text-danger"></span> 
                    </div>
                    <div class = "col-12">
                         @if (Model.product.Id != 0)
                         {
                            <button type="submit" onclick = "return ValidateInput()" class="btn btn-primary" style="width : 150px">Update</button>
                         }
                        else
                        {
                            <button type="submit" class="btn btn-primary" style="width : 150px">Create</button>
                        }
                        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                                Back To List
                        </a>
                </div>
        </div>
    </div>
    <div class = "col-2 pt-4">
        <img src = "@Model.product.ImageUrl"
            width = "100%" style= "border-radius:5px; border:1px solid #bbb9b9 " />
    </div>
 </form>   
@*to add partial view for cliet side validation*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>

    tinymce.init({
      selector: 'textarea',
      plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
      toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
      toolbar_mode: 'floating',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
    });

        function ValidateInput(){
            if(document.getElementById("uploadBox").Value==""){
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Please Upload an Image!!!!',
                });
                return false;
            }
            return true;
        }
    </script>
}