BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class CategoryController : Controller
    {
        //private readonly ApplicationDbContext _db;
        //private readonly ICategoryRepository _db;
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork db)
        {
            _unitOfWork = db;
        }

        public IActionResult Index()
        {
            //IEnumerable<Category> objCategoryList = _db.Categories; //retreive the category 
            //IEnumerable<Category> objCategoryList = _db.Category.GetAll(); //retreive the category 
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll(); //to use unityof work.
            return View(objCategoryList);
        }

        //Create Functionality
        //GET
        public IActionResult Create() 
        {
            return View();
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Category obj)  //in validation check model is valid or not (Require properties have or not)
        {
            //costom validation
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                //key       error
                //ModelState.AddModelError("CustomError","The DisplayOrder cannot be exactly match the Name.");
                ModelState.AddModelError("Name", "The DisplayOrder cannot be exactly match the Name.");
            }


            //check properties validation 
            if (ModelState.IsValid)     //havor on ModelState and check(Values>Result Values) if any propertie valid or not here 
            {
                //_db.Categories.Add(obj);   //add to category
                _unitOfWork.Category.Add(obj);   //after repo
                //_db.SaveChanges(); //simple use
                //_db.Save(); //after repo
                _unitOfWork.Save(); //after use unitofwork
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index"); 
            }
            return View(obj);
        }



        //Edit/Update Functionality 

        //GET
        public IActionResult Edit(int? id) 
        {
            if (id ==null || id==0)
            {
                return NotFound();
            }
            //way of retreive category
            //var categoryFromDb = _db.Categories.Find(id);  //based on the primary key it find  
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.ID == id); //not throw exception and return first element of the list 
            //var categoryFromDbFirst = _db.GetFirstOrDefault(u=>u.ID == id); //after repo
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.ID == id); //after use unitofwork
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.ID == id); //throw an exception
            if (categoryFromDbFirst == null) 
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken] 
        public IActionResult Edit(Category obj)  //in validation check model is valid or not (Require properties have or not)
        {
            //costom validation
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                //key       error
                //ModelState.AddModelError("CustomError","The DisplayOrder cannot be exactly match the Name.");
                ModelState.AddModelError("Name", "The DisplayOrder cannot be exactly match the Name.");

            }


            //check properties validation 
            if (ModelState.IsValid)     //havor on ModelState and check(Values>Result Values) if any propertie valid or not here 
            {
                //_db.Categories.Update(obj); //update for this 
                //_db.Update(obj); //after use repo
                _unitOfWork.Category.Update(obj); //after use unitofwork
                //_db.SaveChanges();
                //_db.Save(); //after use repo
                _unitOfWork.Save(); //after use unitofwork
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }



        //update functionality
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //way of retreive category
            //var categoryFromDb = _db.Categories.Find(id);  //based on the primary key it find  
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.ID == id); //not throw exception and return first element of the list 
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.ID == id); //after use repo
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.ID == id); //throw an exception
            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }

        //Post
        [HttpPost,ActionName("Delete")]
        [AutoValidateAntiforgeryToken]  
        public IActionResult DeletePOST(int? id)  //in validation check model is valid or not (Require properties have or not)
        {
            //var obj = _db.Categories.Find(id);
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.ID == id); //add line after use repo
            if (obj == null)
            {
                return NotFound();
            }

            //_db.Categories.Remove(obj); //remove for this 
            _unitOfWork.Category.Remove(obj); //add after repo
            //_db.SaveChanges();
            _unitOfWork.Save(); //add after unitofwork
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index"); 
        }
    }

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
   
    public CompanyController(IUnitOfWork db)
    {
        _unitOfWork = db;
       
    }
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Upsert(int? id)
    {
        Company company = new();
        if (id == null || id == 0)
        {
            return View(company);
        }
        else
        {
            company=_unitOfWork.Company.GetFirstOrDefault(u=>u.Id == id);
            return View(company);
        }
        
    }
    //Post
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public IActionResult Upsert(Company obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            if (obj.Id == 0)
            {
                _unitOfWork.Company.Add(obj);
                TempData["success"] = " Company added successfully";
            }
            else
            {
                _unitOfWork.Company.Update(obj);
                TempData["success"] = " Company updated successfully";
            }

            _unitOfWork.Save();
           
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    #region API CALLS

    [HttpGet]

    public IActionResult GetAll()
    {
        var companyList = _unitOfWork.Company.GetAll();
        return Json(new { data = companyList });

    }
    [HttpDelete]
    public IActionResult Delete(int? id) 
    {
        var obj = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id); 
        if (obj == null)
        {
            return Json(new {success=false, message = "Error while deleting"});
        }
       
        _unitOfWork.Company.Remove(obj); ;
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete Successful" });
    }
    #endregion
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public ProductController(IUnitOfWork db, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = db;
        _hostEnvironment = hostEnvironment;
    }
    public IActionResult Index()
    {
        //  IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll(); 
        //  return View(objProductList);
        return View();
    }
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new()
        {
            product = new(),

            CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.ID.ToString()
            }),
            CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
            {
                Text = i.CoverType_Name,
                Value = i.CoverType_Id.ToString()
            }),
        };

        if (id == null || id == 0)
        {
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            return View(productVM);
        }
        else
        {
            productVM.product=_unitOfWork.Product.GetFirstOrDefault(u=>u.Id == id);
            return View(productVM);
        }
        
    }
    //Post
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Images\products");
                var extension = Path.GetExtension(file.FileName);
                if (obj.product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.product.ImageUrl = @"\Images\Products\" + fileName + extension;
            }
            if (obj.product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.product);
            }
            else
            {
                _unitOfWork.Product.Update(obj.product);
            }

            _unitOfWork.Save();
            TempData["success"] = " Product added successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    #region API CALLS

    [HttpGet]

    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
        return Json(new { data = productList });

    }
    [HttpDelete]
    public IActionResult Delete(int? id) 
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id); 
        if (obj == null)
        {
            return Json(new {success=false, message = "Error while deleting"});
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Product.Remove(obj); ;
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete Successful" });
    }
    #endregion
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootswatcheTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/> @*add for toast*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel = "stylesheet" href = "//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
             <a class="navbar-brand" href="#">BulkyBook</a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarColor02">
             <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                    <div class="dropdown-menu">
                        <a class = "dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                        <a class = "dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        <div class="dropdown-divider"></div>
                        <a class = "dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class=nav-link asp-area="Admin" asp-controller = "Order" asp-action="Index">
                         Manage Order
                    </a>
                </li>
                <li class="nav-item">
                    <a class=nav-link asp-area="Customer" asp-controller = "Cart" asp-action="Index">
                      <i class="bi bi-cart"></i>
                    </a>
                 </li>
             </ul>
             <partial name="_LoginPartial"/>
            @*<form class="d-flex">
                 <input class="form-control me-sm-2" type="text" placeholder="Search">
                 <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
             </form>*@
            </div>
        </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*<partial name = "_Notification " />*@
            @RenderBody()
        </main>
    </div>
    <footer class=" footer text-muted bg-primary"> @*border-top*@
        <div class="container">
            &copy; 2022 - BulkyBookWeb @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div> 
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src = "//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/hbqj15e39tnwifit52sc6pjzv8cf72jatlpby8032ymd3cer/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src = "~/lib/jquery/dist/jquey.min.js"></script>
    <script src = "//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type = "text/javascript">
         toastr.success('@TempData["Success"]');
    </script>
   
}
@if(TempData["error"] != null)
{
     <script src = "~/lib/jquery/dist/jquey.min.js"></script>
    <script src = "//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type = "text/javascript">
         toastr.error('@TempData["error"]');
    </script>
}